class AppImages {
  static String accountPersonIcon = 'assets/images/account_person_icon.png';
  static String audio = 'assets/images/audio.png';
  static String audioIconHightlight = 'assets/images/audio_icon_selected.png';
  static String backArrow = 'assets/images/back_arrow.png';
  static String beora = 'assets/images/beora.png';
  static String bookmark = 'assets/images/bookmark.png';
  static String clock = 'assets/images/clock.png';
  static String search = 'assets/images/search.png';
  static String googleMicIcon = 'assets/images/google_mic_icon.png';
  static String hamburger = 'assets/images/hamburger.png';
  static String highLightBookmark = 'assets/images/hightlight_bookmark.png';
  static String languageIcon = 'assets/images/language.png';
  static String sideMenuLocationIcon = 'assets/images/side_menu_location.png';
  static String appLogo = 'assets/images/logo.png';

  static String profile = 'assets/images/login.png';
  static String location = 'assets/images/map.png';
  static String home = 'assets/images/home.png';
  static String notification = 'assets/images/notifications_icon.png';
  static String theme = 'assets/images/light_dark.png';
  static String splash = 'assets/images/splash_image.png';
  static String share = 'assets/images/sharing_icon.png';
  static String email = 'assets/images/mail.png';
  static String aboutUs = 'assets/images/info.png';
  static String loginLogout = 'assets/images/login_logout.png';
  static String sideArrow = 'assets/images/side_arrow.png';
  static String profileImage = 'assets/images/profile.png';
  static String videoPlayerIcon = 'assets/images/video_player_icon.jpg';
  static String videoPlayIcon = 'assets/images/video_play_icon.png';
  static String audioPlayIcon = 'assets/images/sound.gif';
  static String audioPlayerIcon = 'assets/images/audio_player_icon.png';
  static String audioPlayer = 'assets/images/audio_player.jpg';
  static String appleMusicIcon = 'assets/images/apple_music_icon.png';
  static String uploadIcon = 'assets/images/upload_icon.png';
  static String dashboard = 'assets/images/dashboard_icon.png';
  static String loginLackground = 'assets/images/login_background.jpeg';
  static String tempURL =
      'https://fastly.picsum.photos/id/237/200/300.jpg?hmac=TmmQSbShHz9CdQm0NkEjx1Dyh_Y984R9LpNrpvH2D_U';
}
